// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { readConnectionString } from "./src/lib/db-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Las migraciones necesitan una conexión de sesión completa (usan locks
    // de advisory y DDL), así que no pueden ir por el pooler de transacciones
    // que usa la app en runtime. DIRECT_URL apunta al session pooler; si no
    // está definida se usa DATABASE_URL, que es el caso en local.
    url:
      readConnectionString(process.env["DIRECT_URL"]) ??
      readConnectionString(process.env["DATABASE_URL"]),
  },
});
